# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: INFO
        com.damienfremont.starter: INFO
        io.github.jhipster: INFO

jwt:
    header: Authorization
    expires_in: 300 # 5 minutes
    mobile_expires_in: 600 # 10 minutes
    secret: XXXXXXYYYU6546546546654654654654654654

spring:
    application:
        name: springboot1-angular5-bootstrap4-starter
    profiles:
        active: prod
        include: swagger
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/springboot1-angular5-bootstrap4-starter
        username: springboot1-angular5-bootstrap4-starter
        password:
    jpa:
        generate-ddl: false
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                ddl-auto: update
                use_second_level_cache: false
                cache.use_query_cache: false
                generate_statistics: false
    data:
        jpa.repositories.enabled: true

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias springboot1-angular5-bootstrap4-starter -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: springboot1-angular5-bootstrap4-starter
# ===================================================================
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
